### ISSUE TITLE
Add support of newer perl versions (i.e. 5.26.2)

### ISSUE THREAD

**Issue by rcavezzale** [Tontonitch/interfacetable_v3t#45]
Hi,

I have an problem to run the script, unfortunately I don't understand what is the issue

nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ uname -a
Linux mi-sg3-nagios-01 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ ./check_interface_table_v3t.pl -V
Array found where operator expected at ./check_interface_table_v3t.pl line 67, near "@max_plugin_output_length@;"
        (Missing operator before @;?)
Global symbol "@max_plugin_output_length" requires explicit package name (did you forget to declare "my @max_plugin_output_length"?) at ./check_interface_table_v3t.pl line 67.
syntax error at ./check_interface_table_v3t.pl line 78, next char @
Can't redeclare "my" in "my" at ./check_interface_table_v3t.pl line 89, near "my"
BEGIN not safe after errors--compilation aborted at ./check_interface_table_v3t.pl line 5534.
nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$

Let me know
Best Regards

**Comment by Tontonitch** [comment]
Hello,
@max_plugin_output_length@ is a variable that should be replaced by a value during the installation phase (./configure,...)
Did you well follow the installation instructions? No error message?
BR,
Yannick

**Comment by rcavezzale** [comment]
nms@mi-sg3-nagios-01:/tmp/interfacetable_v3t$ sudo ./configure --prefix=/usr/local/interfacetable_v3t --with-htmlurl=http://myserver/interfacetable_v3t
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make sets $(MAKE)... yes
checking for strip... /usr/bin/strip
checking for cp... /bin/cp
checking for touch... /usr/bin/touch
checking for grep... /bin/grep
checking for perl... /usr/bin/perl
checking for snmpget... /usr/bin/snmpget
checking for snmpwalk... /usr/bin/snmpwalk
checking for sudo... /usr/bin/sudo
checking for a BSD-compatible install... /usr/bin/install -c
checking for Net::SNMP perl module... found
checking for Config::General perl module... found
checking for Data::Dumper perl module... found
checking for Getopt::Std perl module... found
checking for CGI perl module... found
checking for Storable perl module... found
checking for Sort::Naturally perl module... found
checking for Exception::Class perl module... found
checking for Time::HiRes perl module... found
checking for Encode perl module... found
configure: creating ./config.status
config.status: creating subst
config.status: creating Makefile
config.status: creating sbin/Makefile
config.status: creating etc/Makefile
config.status: creating lib/Makefile
config.status: creating libexec/Makefile
config.status: creating share/Makefile
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.


*** Configuration summary for interfacetable_v3t 1.00 04-01-2019 ***:

 Global installation directories:
 --------------------------------
                           ${prefix}:  /usr/local/interfacetable_v3t
                      ${exec_prefix}:  /usr/local/interfacetable_v3t
         libdir (for perl libraries):  ${exec_prefix}/lib
        sysconfdir (for config file):  ${prefix}/etc
 datarootdir (for html, css, js,...):  ${prefix}/share
 Note: exec_prefix, libdir, sysconfdir and datadir can be changed for fine tuned installations

 Nagios & related options:
 -------------------------
                  Install user/group:  nagios,nagios
                     Nagios base dir:  /usr/local/nagios
                  Nagios libexec dir:  /usr/local/nagios/libexec
                      Nagios etc dir:  /usr/local/nagios/etc
    InterfaceTable_v3t addon CGI dir:  /usr/local/interfacetable_v3t/sbin
    InterfaceTable_v3t addon CGI url:  /interfacetable_v3t/cgi-bin
   InterfaceTable_v3t addon HTML url:  http://myserver/interfacetable_v3t
                     Cache files dir:  /tmp/.ifCache
                     State files dir:  /tmp/.ifState

 Graphing options:
 -----------------
              Graphing solution name:  pnp4nagios
               Graphing solution url:  /pnp4nagios

 Apache & sudo options:
 ----------------------
                   Apache conf.d dir:  ${prefix}/etc/apache-conf.d/
                         Apache User:  www-data
                     Apache AuthName:  Nagios Access
                     Apache AuthFile:  /usr/local/nagios/etc/htpasswd.users
                        Sudoers file:  /etc/sudoers

 Other options:
 ----------------------
          Port performance data unit:  bps
            MAX_PLUGIN_OUTPUT_LENGTH:  8192

 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING - PLEASE READ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !! Interfacetable_v3t release 0.05 introduces some important changes in the way traffic      !!
 !! statistics are calculated and reported.                                                   !!
 !! In previous versions, the statistics were collected from counters and were written as     !!
 !! counters in the performance data. The graphing solution, in charge of processing the      !!
 !! performance data, had to insertcounters in the rrd files. During this rrd update, the     !!
 !! traffic rate (in bits/octets per second) was calculated. With this method, there is no    !!
 !! way to avoid abnormal statistics to be inserted in the rrd files.                         !!
 !! In this new 0.05 release, the statistics are still collected from counters, but the rates !!
 !! (usually bps) are calculated and transmitted to performance data (no more as counters).   !!
 !! The graphing solution, in charge of processing the performance data, have to insert bps   !!
 !! values in the rrd files. With this method, abnormal statistics are not transmitted to the !!
 !! graphing solution, leaving the rrd files only with consistent statistics.                 !!
 !! This new method is now default one in this new release of the plugin. The old method is   !!
 !! still available but should be removed in future versions of the plugin.                   !!
 !!                                                                                           !!
 !! Important notes:                                                                          !!
 !!  * if you are proceeding to a new installation of the interfacetable_v3t plugin,          !!
 !!    everything should be okay, the new default method will be used.                        !!
 !!  * if you are upgrading an existing installation of the interfacetable_v3t plugin:        !!
 !!    - by default, the new method will be used.                                             !!
 !!      YOU WILL NEED TO CONVERT THE EXISTING RRD FILES! See the upgrade procedure at        !!
 !!      http://www.tontonitch.com/tiki/tiki-index.php?page=Nagios+plugins+-+interfacetable_v !!
 !!      3t+-+documentation+-+0.05+-+Upgrade&structure=Nagios+plugins+-+interfacetable_v3t+-+ !!
 !!      documentation+-+0.05                                                                 !!
 !!    - or you can still use the old method                                                  !!
 !!       a) during the installation by using the configure option --with-portperfunit=bit    !!
 !!       b) or when running the plugin by using the plugin option --portperfunit=bit         !!
 !!      Please KEEP IN MIND that switching from one method to another imply the conversion   !!
 !!      of the rrd files as a prerequisite!!!                                                !!
 !!      Please KEEP IN MIND that the old method returning counters as performance data will  !!
 !!      be REMOVED from future releases                                                      !!
 !!  * the option --portperfunit cannot take the value 'octet' anymore. This option has been  !!
 !!    removed as not used, for better maintenance, and in the forcast of the unique unit     !!
 !!    'bps' in future releases. If you use it, please contact me.                            !!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING - PLEASE READ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Review the options above for accuracy. If they look okay,
type 'make install' to install the software.
type 'make fullinstall' to install the software and environment configs (apache, sudo).

nms@mi-sg3-nagios-01:/tmp/interfacetable_v3t$ sudo make fullinstall
cd ./sbin && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/sbin'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/sbin
/usr/bin/install -c -m 755 -o nagios -g nagios InterfaceTableReset_v3t.cgi /usr/local/interfacetable_v3t/sbin/InterfaceTableReset_v3t.cgi
make[1]: Leaving directory '/tmp/interfacetable_v3t/sbin'
cd ./etc && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/etc'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/etc
/usr/bin/install -c -m 644 -o nagios -g nagios settings.cfg-sample /usr/local/interfacetable_v3t/etc/settings.cfg-sample
make[1]: Leaving directory '/tmp/interfacetable_v3t/etc'
cd ./libexec && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/libexec'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/nagios/libexec
/usr/bin/install -c -m 755 -o nagios -g nagios check_interface_table_v3t.pl /usr/local/nagios/libexec/check_interface_table_v3t.pl
make[1]: Leaving directory '/tmp/interfacetable_v3t/libexec'
cd ./lib && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/lib'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/lib
for file in ./*.pm; \
    do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/interfacetable_v3t/lib; done
make[1]: Leaving directory '/tmp/interfacetable_v3t/lib'
cd ./share && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/share'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/share
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/share/css
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/share/img
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/share/js
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/share/tables
for file in css/*; \
    do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/interfacetable_v3t/share/css; done
for file in img/*; \
    do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/interfacetable_v3t/share/img; done
for file in js/*; \
    do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/interfacetable_v3t/share/js; done
for file in tables/*; \
    do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/interfacetable_v3t/share/tables; done
make[1]: Leaving directory '/tmp/interfacetable_v3t/share'
cd ./etc && make install-apache-config
make[1]: Entering directory '/tmp/interfacetable_v3t/etc'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/etc/apache-conf.d/
/usr/bin/install -c -m 644 interfacetable_v3t.conf.httpd /usr/local/interfacetable_v3t/etc/apache-conf.d//interfacetable_v3t.conf

*** Apache config file installed. The apache service needs to be reloaded. ***

make[1]: Leaving directory '/tmp/interfacetable_v3t/etc'
cd ./etc && make install-sudo-config
make[1]: Entering directory '/tmp/interfacetable_v3t/etc'
#TODO sudoers.d
SUDOERS_OK=0
if [ "/etc/sudoers" != "no" ] ; then \
    chmod 0640 /etc/sudoers; \
    if test -w /etc/sudoers; then \
        if [ `/bin/grep -c "/usr/local/interfacetable_v3t/sbin/InterfaceTableReset" /etc/sudoers` -eq 0 ] ; then \
            echo 'www-data ALL=(ALL) NOPASSWD: /usr/local/interfacetable_v3t/sbin/InterfaceTableReset_v3t.cgi' >> /etc/sudoers; \
            SUDOERS_OK=1; \
            echo ""; \
            echo "***************************"; \
            echo ""; \
            echo "Sudo configuration updated."; \
            echo ""; \
            echo "***************************"; \
            echo ""; \
        else \
            echo ""; \
            echo "****************************************************************************"; \
            echo ""; \
            echo "NOTICE: A rule concerning InterfaceTableReset_v3t.cgi is already configured."; \
            echo "        Assuming that sudo configuration have been already done."; \
            echo ""; \
            echo "****************************************************************************"; \
            echo ""; \
        fi; \
    else \
        echo ""; \
        echo "*********************************************************************************"; \
        echo ""; \
        echo "WARNING: The file udoers cannot be found, or is not writable"; \
        echo "         You need to add the following rule manually:"; \
        echo '         www-data ALL=(ALL) NOPASSWD: /usr/local/interfacetable_v3t/sbin/InterfaceTableReset_v3t.cgi'; \
        echo ""; \
        echo "*********************************************************************************"; \
        echo ""; \
    fi; \
    chmod 0440 /etc/sudoers; \
else \
    echo ""; \
    echo "********************************************************************************"; \
    echo ""; \
    echo "NOTICE: The sudoers file was neither automatically found nor manually specified."; \
    echo "        You need to add the following rule manually:"; \
    echo '        www-data ALL=(ALL) NOPASSWD: /usr/local/interfacetable_v3t/sbin/InterfaceTableReset_v3t.cgi'; \
    echo ""; \
    echo "********************************************************************************"; \
    echo ""; \
fi

****************************************************************************

NOTICE: A rule concerning InterfaceTableReset_v3t.cgi is already configured.
        Assuming that sudo configuration have been already done.

****************************************************************************

make[1]: Leaving directory '/tmp/interfacetable_v3t/etc'

**Comment by Tontonitch** [comment]
ok. I see.
what's your perl version and OS?
I will perform some tests give you some news quickly.

**Comment by rcavezzale** [comment]
Only to clarify the make process works because i use mv command to rename the file example
InterfaceTableReset_v3t.cgi.in to InterfaceTableReset_v3t.cgi 
because I shows this error:

nms@mi-sg3-nagios-01:/tmp/interfacetable_v3t$ sudo make install
cd ./sbin && make install
make[1]: Entering directory '/tmp/interfacetable_v3t/sbin'
/usr/bin/install -c -m 755 -o nagios -g nagios -d /usr/local/interfacetable_v3t/sbin
/usr/bin/install -c -m 755 -o nagios -g nagios InterfaceTableReset_v3t.cgi /usr/local/interfacetable_v3t/sbin/InterfaceTableReset_v3t.cgi
/usr/bin/install: cannot stat 'InterfaceTableReset_v3t.cgi': No such file or directory
Makefile:49: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/tmp/interfacetable_v3t/sbin'
Makefile:83: recipe for target 'install' failed
make: *** [install] Error 2

nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-gnu-thread-multi
(with 63 registered patches, see perl -V for more detail)

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.


nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by rcavezzale** [comment]
you are my hero

nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ ./check_interface_table_v3t.pl -V
./check_interface_table_v3t.pl (1.00)
This nagios plugin comes with ABSOLUTELY NO WARRANTY. You may redistribute
copies of this plugin under the terms of the GNU General Public License version 3 (GPLv3).
nms@mi-sg3-nagios-01:/usr/local/nagios/libexec$ vim check_interface_table_v3t.pl

thanks so much for your great support :)
have a nice weekend

Best Regard
CR
