### ISSUE TITLE
Nagios Reporting UNKNOWN - SNMP error: No response from remote host on interfacetable

### ISSUE THREAD

**Issue by Vcpdrago** [Tontonitch/interfacetable_v3t#53]
Good Afternoon all, 
I am having an issue with the Interfacetable plugin. I have used this before and it works great. Recently we have upgraded the network to Cisco Catalyst 9300 and 9500's running IOS-XE ver 16.6.5. I was thinking that it was the OS version and platform but after running the command with -vvvvv I am not seeing any errors and seeing the switch return values. I can browse to the service and see that the table had been built when manually executed but will not update when nagios executes the command. Has anyone faced this issue before? Any ideas where to start? Any help is appreciated. 

[DEBUG-InterfaceTablev3t.txt](https://github.com/Tontonitch/interfacetable_v3t/files/4087973/DEBUG-InterfaceTablev3t.txt)

Thank You,
VCP

**Comment by Tontonitch** [comment]
Hello,
These are quite big switches with plenty of interfaces. From your logs, I see 264 ports. I guess you are facing timeouts when launched though nagios. How much time does the command takes when launched in command line?
I have a similar switch at work, I will check how I have configured the related icinga/nagios service. Anyway, it's a question of playing with the --timeout and --snmp-timeout parameters.

**Comment by Vcpdrago** [comment]
Hi, 
When I launch it from cli it takes about 5 to 10 seconds to reply. It seem pretty responsive but never-the-less just will not fly even when specifying snmp time out 50s and timeout to 60s. I am going to go back and retrace my steps and make sure I installed this correctly. I am not able to pull the graph from the table so I have got some issues here. In any event, let me know what you find out and I will update tomorrow. Thank You for the help Tontonitch!

**Comment by Tontonitch** [comment]
I've a C3750E with 216 ports. I use -2 --64bits --timeout 40, nothing else that could influence a timeout.
To show you the generated command: 
`/usr/lib64/nagios/plugins/check_interface_table_v3t --perfdataservicedesc Interface status -r -h XXXXXXXXXX -f -e 'Null0','InLoopBack0' -H XXXXXXXXXX -C XXXXXXXXXXXX -2 --wt 100,100,-1 --wp 1 --tp ifOperStatus --timeout 40 --table-split --64bits --perfdatadir /var/spool/icinga2/perfdata --nodetype cisco --htmltablelinktarget _blank --ep PRINTER,LPT,DOWNLINK --duplex --delta 600 --ct 100,500,-1 --cp 1 --alias-matching --alias --accessmethod telnet
`

Also, be sure to use the --perfdatadir option (and --perfdataservicedesc) to directly write the perfdata in the pnp spool directory (if you use pnp as a graphing solution) as the amount of perfdata could be too big and trucated by nagios.

**Comment by Tontonitch** [comment]
Hello,
Are you still facing the issue?

**Comment by Tontonitch** [comment]
Closing as no answeer
