### ISSUE TITLE
Support configure with perl version 5.26 and newer

### ISSUE THREAD

**Issue by mdicss** [Tontonitch/interfacetable_v3t#63]
Hi
I had problems running 'configure' and 'make install', as there are regular expressions somewhere, that are no longer supported in perl versions beginning with 5.26, see:
https://perldoc.perl.org/5.26.0/perldelta#Unescaped-literal-%22%7B%22-characters-in-regular-expression-patterns-are-no-longer-permissible
As I'm not often using configure and make, I did not yet find the source of the problem. The output of configure is:

...
 config.status: creating subst
 config.status: creating Makefile
 config.status: creating sbin/Makefile
 config.status: creating etc/Makefile
 config.status: creating lib/Makefile
 config.status: creating libexec/Makefile
 config.status: creating share/Makefile
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
 Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\@{ <-- HERE prefix}\@/ at subst line 110.
...

Directories sbin, lib etc. are then created in the wrong place and files are missing. It would be nice to have this fixed. Are there any plans for new software versions?

Best Regards
Matthias

**Comment by Tontonitch** [comment]
Ok, I have a environment with perl 5.30 I will check there.
I do not rebuild often the makefiles as it did not change since a while, all modifications concerned the plugin perl script directly, so it is not a part that I test often. Thanks for reporting.

**Comment by Tontonitch** [comment]
Should be fixed with commit 759c645b37ed2b27b3809c94ab5bf22dcf1b5f42.

**Comment by Tontonitch** [comment]
tested and works fine with perl v5.30.0 on Ubuntu 20.04.6
