### ISSUE TITLE
File xx.xml not found

### ISSUE THREAD

**Issue by monitoringjunkie** [Tontonitch/interfacetable_v3t#65]
Hello,

I am using check_interface_table_v3t.pl in version 1.0 under Icinga.
The server has 35 interfaces, but at 5 are not mapped perfdata.
Message:
 
**If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP__5.xml not found ---> Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (5)
If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP__11.xml not found ---> Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (11)**

The rrd files are created.
Example:

**Interface-Table_If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_11__check_interface_table_port__BpsIn.rrd
or
Interface-Table_If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_5__check_interface_table_port__PpsInDiscard.rrd**

Unfortunately, there are no XML files for these interfaces.
But I can find the connection to **rrd** files in the interface-table.xml file.

 _<DATASOURCE>
    <TEMPLATE>check_interface_table_global</TEMPLATE>
    <RRDFILE>/var/lib/pnp4nagios/perfdata/GHL-CKP-FW1-----TEST/Interface-Table_If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_5__check_interface_table_port__BpsIn.rrd</RRDFILE>
    <RRD_STORAGE_TYPE>MULTIPLE</RRD_STORAGE_TYPE>
    <RRD_HEARTBEAT>8460</RRD_HEARTBEAT>
    <IS_MULTI>1</IS_MULTI>
    <DS>1</DS>
    <NAME>If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_5__check_interface_table_port__BpsIn</NAME>
    <LABEL>If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_5::check_interface_table_port::BpsIn</LABEL>_

or

 _<DATASOURCE>
    <TEMPLATE>check_interface_table_global</TEMPLATE>
    <RRDFILE>/var/lib/pnp4nagios/perfdata/GHL-CKP-FW1-----TEST/Interface-Table_If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_11__check_interface_table_port__BpsIn.rrd</RRDFILE>
    <RRD_STORAGE_TYPE>MULTIPLE</RRD_STORAGE_TYPE>
    <RRD_HEARTBEAT>8460</RRD_HEARTBEAT>
    <IS_MULTI>1</IS_MULTI>
    <DS>1</DS>
    <NAME>If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_11__check_interface_table_port__BpsIn</NAME>
    <LABEL>If_Intel_Corporation_Ethernet_Controller_X710_for_10GbE_SFP+_11::check_interface_table_port::BpsIn</LABEL>_

What is the problem here?
Is the interface name blame – sign +?
How can I solve it?

All perfdata from other interfaces are displayed without issues.

Thx

**Comment by monitoringjunkie** [comment]
Update:

All other interfaces are shorter, and they look like this:

_Intel Corporation I350 Gigabit Network Connection (4)
Intel Corporation I350 Gigabit Network Connection (6)_

**Comment by Tontonitch** [comment]
Do you confirm you are using the latest version v1.01 ? Indeed, e0cf3b37fa624fb618a4c545459e475d6c0e5dcd  introduced a fix for handling interfaces with "+" character.

**Comment by monitoringjunkie** [comment]
hello Tontonitch,

Perfect.
Works perfectly

Thank you.
